### ISSUE TITLE
Pro 7, Fedora 36 Bootstrap Command failed with Status 127 

### ISSUE THREAD

**Issue by ArtemisFowl-San** [quo/iptsd#11]
When I try and run the meson build command it runs fine until it aborts at this failure. 

subprojects/hidrd/meson.build:7:0: ERROR: Command "/home/[name of user]/iptsd/subprojects/hidrd/bootstrap" failed with status 127.

From what I can tell from a quick internet search this appears to be because the command is not recognized as such. 

These are the meson logs 
[meson-log.txt](https://github.com/quo/iptsd/files/9144803/meson-log.txt)

**Comment by NP-chaonay** [comment]
from error

it not found command, autoreconf

idk if this command available to installing in your system software repo

**Comment by ArtemisFowl-San** [comment]
Thanks for the help.

 I installed the following package to allow for the autoreconf command

 autoconf-2.71-2.fc36.noarch

Now when I execute the build command, I get this error 
subprojects/hidrd/meson.build:7:0: ERROR: Command "/home/[name of user] /iptsd/subprojects/hidrd/bootstrap" failed with status 2.


These are the meson logs.

[meson-log.txt](https://github.com/quo/iptsd/files/9151129/meson-log.txt)

**Comment by StollD** [comment]
You also need the automake package. Alternatively, you can run `sudo dnf builddep iptsd.spec`, and then run meson without `--wrap-mode=forcefallback`.

Also, you are building linux-surface/iptsd, but this is quo/iptsd. If you want quo's iptsd, you cloned the wrong repo.
