### ISSUE TITLE
Intel Precise Touch & Stylus not working on Surface Pro 8

### ISSUE THREAD

**Issue by AnotherInfiniteLoop** [quo/iptsd#17]
I have a new Surface Pro 8. Installed Zorin OS and linux-surface kernel. Initially touchscreen didn't work, but fixed it with the steps from quo/ithc-linux. Only thing that is not working now is Intel Precise Touch & Stylus. I followed the steps from quo/iptsd. Multitouch and Stylus work after running 'sudo build/src/daemon/iptsd' command from 'Building' paragraph. But it doesn't work anymore after the steps from 'Installing' paragraph. 

uname -a:
Linux ABC 6.0.9-surface #1 SMP PREEMPT_DYNAMIC Thu Nov 24 19:45:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

systemctl status iptsd returns this:
iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-12-01 10:03:54 CET; 7h ago
       Docs: https://github.com/linux-surface/iptsd
    Process: 1147 ExecStart=/usr/local/bin/iptsd (code=exited, status=127)
   Main PID: 1147 (code=exited, status=127)

dec 01 10:03:54 ABC systemd[1]: Started Intel Precise Touch & Stylus Daemon.
dec 01 10:03:54 ABC iptsd[1147]: /usr/local/bin/iptsd: error while loading shared libraries: libfmt.so: cannot open shared object file: No such file or directory
dec 01 10:03:54 ABC systemd[1]: iptsd.service: Main process exited, code=exited, status=127/n/a
dec 01 10:03:54 ABC systemd[1]: iptsd.service: Failed with result 'exit-code'.

Any idea what's going on?

**Comment by NP-chaonay** [comment]
quo/iptsd is deprecated (see the README.md in that quo/iptsd repo)

using linux-surface/iptsd instead
> (I dont mean install from package manager repo of linux-surface, I mean you can grab prebuilt from action tab in that github repo and goto latest sucessful workflow then choose file that nearest to your distribution)

> (idk is zorin based on Ubuntu, if yes and nothing much changed, it should be debain, but not sure btw)

before install, pls see for detalied instrution

> 1) do the part "message A"
> 2) reinstall userspace driver from (at this moment) github linux-surface/iptsd  ; this can be done by getting from prebuilt
> 3) after that, setting /etc/ipts.conf if you want and thenthen reboot
> 
> 4) if it dont work then apply kernel parameter intremap=nosid
> 
> 
> ### ,message A
> 0) backup ipts.conf config file and delete it
> 1) download source from linux-surface/iptsd and open terminal on source directory
> 2) run this (# mean required root)
> 
> ```
> $ meson build
> # ninja -C build uninstall
> ```

**Comment by NP-chaonay** [comment]
@AnotherInfiniteLoop

**Comment by AnotherInfiniteLoop** [comment]
> quo/iptsd is deprecated (see the README.md in that quo/iptsd repo)
> 
> using linux-surface/iptsd instead
> 
> > (I dont mean install from package manager repo of linux-surface, I mean you can grab prebuilt from action tab in that github repo and goto latest sucessful workflow then choose file that nearest to your distribution)
> 
> > (idk is zorin based on Ubuntu, if yes and nothing much changed, it should be debain, but not sure btw)
> 
> before install, pls see for detalied instrution
> 
> > 1. do the part "message A"
> > 2. reinstall userspace driver from (at this moment) github linux-surface/iptsd  ; this can be done by getting from prebuilt
> > 3. after that, setting /etc/ipts.conf if you want and thenthen reboot
> > 4. if it dont work then apply kernel parameter intremap=nosid
> > 
> > ### ,message A
> > 
> > 0. backup ipts.conf config file and delete it
> > 1. download source from linux-surface/iptsd and open terminal on source directory
> > 2. run this (# mean required root)
> > 
> > ```
> > $ meson build
> > # ninja -C build uninstall
> > ```

Ok, have different issue now. But if needed I'll ask in surface-linux repo.  Thx for your help!
