### ISSUE TITLE
multitouch/pen support not working (SP8 Ubuntu)

### ISSUE THREAD

**Issue by LovisR** [quo/iptsd#18]
so i installed ubuntu on my SP8 recently and got some guidance off a video. when i built iptsd as described here, i could use multitouch for a bit, but when i then tried installing iptsd, my multitouch didnt work anymore. i saw a similar open issue, but since they actually had it working, but it stopped. i assume my issue is a different one. i still tried the fix suggested there but after changin my iptsd.service file to
```
 [Unit]
Description=Intel Precise Touch & Stylus Daemon
Documentation=https://github.com/linux-surface/iptsd

[Service]
Type=simple
ExecStart=/usr/local/bin/iptsd

```
and restarting it still didnt work and when i type
`systemctl status iptsd`
it returns
```
○ iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

```

**Comment by quo** [comment]
This repository is very outdated.

Please try the master branch of the official iptsd. Go to https://github.com/linux-surface/iptsd/actions, then click the topmost run, then download the appropriate artifact ("debian-latest" should work for Ubuntu).

If the package doesn't work, please try manually compiling and installing the official master branch (https://github.com/linux-surface/iptsd/).

**Comment by LovisR** [comment]
im very sorry for my stupidity, but i have no clue how i would install the appropirate artifact after downloading it oO is it the same as what is described in the readme of this package?

**Comment by quo** [comment]
If you unzip the artifact there's a .deb file inside. I think on Ubuntu you can just double click the .deb and it will give you an option to install it.

Probably best to fully remove your current iptsd first (at a minimum remove the existing service file).

**Comment by LovisR** [comment]
thank you very much, installed it and multitouch works now <3
