### ISSUE TITLE
Support for building on Android

### ISSUE THREAD

**Issue by hmtheboy154** [quo/iptsd#4]
Hello, I am trying to port this iptsd alongside with the ithc kernel module to support SP7+/SP8 touchscreen on Android-x86 (and also derivative like BlissOS, ProjectSakura-x86). I already ported the original iptsd and it does work, however when it comes to this version of iptsd it seems like I need extra work to do. I've prepared libinih, fmt (AOSP have it on external fmtlib), Microsoft-GSL ([upstream this old repo of AOSP](https://android.googlesource.com/platform/external/Microsoft-GSL/) and also spdlog. However it seems like both spdlog and this iptsd can't be able to compile and it show a lot of error

Here is the result I compiled with spdlog relying on external fmt
[spdlog.log](https://github.com/quo/iptsd/files/8840466/spdlog.log)
Here is the result I compiled with only spdlog headers
[spdlog_ho.log](https://github.com/quo/iptsd/files/8840475/spdlog_ho.log)

Seems like apart from iptsd error, there's also spdlog error. I'll try to file another Issue on spdlog repo.

**Comment by quo** [comment]
I don't know much about building native code on Android, but some of the errors are probably due to using different versions of spdlog and fmt. Can you not just use the bundled versions?

I also see errors due to usage of C++ exceptions. It looks like you can enable exception support in the NDK: https://developer.android.com/ndk/guides/cpp-support.html#xp

**Comment by NP-chaonay** [comment]
> Hello, I am trying to port this iptsd alongside with the ithc kernel module to support SP7+/SP8 touchscreen on Android-x86 (and also derivative like BlissOS, ProjectSakura-x86). I already ported the original iptsd and it does work, however when it comes to this version of iptsd it seems like I need extra work to do. I've prepared libinih, fmt (AOSP have it on external fmtlib), Microsoft-GSL ([upstream this old repo of AOSP](https://android.googlesource.com/platform/external/Microsoft-GSL/) and also spdlog. However it seems like both spdlog and this iptsd can't be able to compile and it show a lot of error
> 
> Here is the result I compiled with spdlog relying on external fmt [spdlog.log](https://github.com/quo/iptsd/files/8840466/spdlog.log) Here is the result I compiled with only spdlog headers [spdlog_ho.log](https://github.com/quo/iptsd/files/8840475/spdlog_ho.log)
> 
> Seems like apart from iptsd error, there's also spdlog error. I'll try to file another Issue on spdlog repo.

I think this should easy if building on x86 Android
just we have /dev/ithc and change file structure from /etc and /usr to become inside /system or appropriate folder.

then this should go well

now the  problem I little worry is ithc-linux and Input API of Android,


for ithc; if driver api is compatible to modified linux kernel for android, if yes then no ported required, just making module and doing modprobe stuff in Android and doing modified iptsd  installation should work.

for Android input API, I guess it using the same way as Linux desktop used, I mean through Linux Input Event. In that case everything above should go fine.

**Comment by hmtheboy154** [comment]
> > Hello, I am trying to port this iptsd alongside with the ithc kernel module to support SP7+/SP8 touchscreen on Android-x86 (and also derivative like BlissOS, ProjectSakura-x86). I already ported the original iptsd and it does work, however when it comes to this version of iptsd it seems like I need extra work to do. I've prepared libinih, fmt (AOSP have it on external fmtlib), Microsoft-GSL ([upstream this old repo of AOSP](https://android.googlesource.com/platform/external/Microsoft-GSL/) and also spdlog. However it seems like both spdlog and this iptsd can't be able to compile and it show a lot of error
> > Here is the result I compiled with spdlog relying on external fmt [spdlog.log](https://github.com/quo/iptsd/files/8840466/spdlog.log) Here is the result I compiled with only spdlog headers [spdlog_ho.log](https://github.com/quo/iptsd/files/8840475/spdlog_ho.log)
> > Seems like apart from iptsd error, there's also spdlog error. I'll try to file another Issue on spdlog repo.
> 
> I think this should easy if building on x86 Android just we have /dev/ithc and change file structure from /etc and /usr to become inside /system or appropriate folder.
> 
> then this should go well
> 
> now the problem I little worry is ithc-linux and Input API of Android,
> 
> for ithc; if driver api is compatible to modified linux kernel for android, if yes then no ported required, just making module and doing modprobe stuff in Android and doing modified iptsd installation should work.
> 
> for Android input API, I guess it using the same way as Linux desktop used, I mean through Linux Input Event. In that case everything above should go fine.

compiling them is a roadblock for me, I don't think there will be problem after that. The main `iptsd` for older Surface can already work well with the `ipts` kernel module
