### ISSUE TITLE
SP7 pen not working

### ISSUE THREAD

**Issue by Freek07** [quo/iptsd#6]
Hi,

I just compiled, installed and started the daemon; connected the Surface pen via BT - and it still doesn't work. 
Xev reports button press on eraser button (as it did before), bluetooth widget reports pen battery percentage (as it did before) but the pen doesn't work.

Compilation was without any issues, the daemon runs. 

Here's the log:

```
Jun 15 09:24:21 MaySurface systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Jun 15 09:24:21 MaySurface iptsd[7421]: [09:24:21.700] [info] Connected to device 045E:099F
Jun 15 09:24:21 MaySurface kernel: [ 3807.501789] input: IPTS Touch as /devices/virtual/input/input55
Jun 15 09:24:21 MaySurface kernel: [ 3807.502125] input: IPTS Stylus as /devices/virtual/input/input56
Jun 15 09:24:22 MaySurface kwin_x11[1195]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 44704, resource id: 88080389, major code: 18 (ChangeProperty), minor code: 0
```
(the last one is always present when starting iptsd! Maybe that's the reason?)

Here's the excerpt from dmesg:
```
[    4.731235] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[    4.733455] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:099F ready
```

Am I missing something or it doesn't work? Should I be using Wayland?
Thanks :)

**Comment by HB9HIL** [comment]
I've got exactly the same result here aswell. SP7, compiling and daemon runs flawless. But pen still doesn't work..

**Comment by quo** [comment]
On SP7 you have to enable the `gen7mt` option for the ipts driver:
`echo options ipts gen7mt | sudo tee /etc/modprobe.d/ipts-gen7mt.conf`
Then reboot (or reload `ipts`).

Also, if you get constant "block" errors, I've just pushed a fix for those (but touch and pen should also work fine without that fix).

**Comment by codewizard1975** [comment]
Thank you for your hard work on this.  Can verify I was able to get the pen working on Deepin Linux 20.6 on Surface Pro 7 without any hickups using non-secure boot setup. 

No go on Fedora 36, touch wouldn't even work.

**Comment by poligarpi** [comment]
I was able to get it to work on Fedora 36 by calling the iptsd binary in /usr/bin/ so created a new service that calls a script that calls the binary and now it works well enough, both multitouch and pen

In other distros I didn't have to do anything but compile and install

**Comment by fisi-pr** [comment]
@poligarpi would you be so kind to share your findings and scripts for fedora. Im having the same problem not being able to run iptsd in userspace.

**Comment by lolerco** [comment]
Same here. Xev with eraser butten worked perfectly as did the daemon and so on, but I can't get the pen to work. Enabeling gen7mt didn't work either. I'm on manjaro btw.

**Comment by fisi-pr** [comment]
Hey, I also installed iptsd per gitclone and instructions to /usr/src and since then the pen works(for fedora 36). Albeit as a mouse, but in xournal++ i can write normally.

**Comment by lolerco** [comment]
So a little update from my part. After switching to Fedora 36, the pen now works splendidly, except I can't seem to get the service to start as "default". It always starts with the one from the official repo and after deleting that (in order to get the experimental version going) no matter what I do, the system won't find iptsd.service. If I copy the lines in a file abc.service, it'll find that but not iptsd, so I have to start the daemon everytime I want to use the pen. Also: Don't try to add it to requiries, it'll destroy EVERYTHING. And make sure to set a root password folks.

**Comment by NP-chaonay** [comment]
> So a little update from my part. After switching to Fedora 36, the pen now works splendidly, except I can't seem to get the service to start as "default". It always starts with the one from the official repo and after deleting that (in order to get the experimental version going) no matter what I do, the system won't find iptsd.service. If I copy the lines in a file abc.service, it'll find that but not iptsd, so I have to start the daemon everytime I want to use the pen. Also: Don't try to add it to requiries, it'll destroy EVERYTHING. And make sure to set a root password folks.

so try to adjust the file /lib/systemd/system/iptsd.service

tobe like this

```
[Unit]
Description=Intel Precise Touch & Stylus Daemon
Documentation=https://github.com/linux-surface/iptsd

[Service]
Type=simple
ExecStart=/usr/local/bin/iptsd
```

this should fix to use quo version of iptsd

note that this perhaps to be replaced when package about iptsd is reinstalled or updated
so you have to do this manually I think, or you could just do reinstalling from repo's readme or just replace that file from [this](https://github.com/quo/iptsd/blob/libqzed/etc/systemd/iptsd.service.in) with some adapt (ex. binary exe file path)
