### ISSUE TITLE
meson build error 

### ISSUE THREAD

**Issue by gu8fb** [quo/iptsd#8]
src/meson.build:60:0 ERROR Git program not found

[meson-log.txt](https://github.com/quo/iptsd/files/9075713/meson-log.txt)

pretty new to this so I apologize in advance if I've missed something obvious

**Comment by NP-chaonay** [comment]
> Git

have binary git (in case you dont know which binary/program, it is from https://git-scm.com) in your path

That binary we commonly called it git binary/program. because it just binary named "git"

commonly use for clone or manage local/remote repo of Git system such as GitHub/GitLab.

**Comment by gu8fb** [comment]
@NP-chaonay yep that works. thanks for being patient with me!
